function res = twobc(ya,yb,para,alpha,r0,Rb)
  psi0 = alpha;
  psi1 = 0.000;
  J0 = para;
  res = [ ya(1)-psi0;... 
          ya(3)-J0;...   
          ya(4)-r0;...   
          yb(1)-psi1;... 
          yb(4)-Rb;...   
          yb(5)-0;...   
          yb(6)+Rb*yb(2)^2/J0^2];  